#!/usr/bin/env python3
"""Retain the canonical type-4 material body and level light initializer."""
from pathlib import Path
import argparse
import re
from extract_dam_guard_chr_scheduler_slice import function_text

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
repo = Path(__file__).resolve().parent.parent
model = (repo / 'src/game/model.c').read_text()
bg = (repo / 'src/game/bg.c').read_text()
light = re.search(r'Lights1 GlobalLight = gdSPDefLights1\([\s\S]*?\);', bg)
assert light is not None
result = ('/* Generated by scripts/generate_model_render_setup.py; do not edit. */\n'
          + light.group().replace('Lights1 GlobalLight', 'static const Lights1 ge_model_level_light')
          + '\n\n' + function_text(model, 'modelApplyRenderModeType4').replace(
              'void modelApplyRenderModeType4', 'static void ge_model_render_type4') + '\n')
target = repo / 'port/include/ge_original_model_render_setup.inc'
if args.check:
    assert target.read_text() == result, 'canonical model render setup drift'
else:
    target.write_text(result)
