#!/usr/bin/env python3
"""Generate the native stage/track music registry from decompiled US tables."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re


def initializer(text: str, declaration: str) -> str:
    start = text.index(declaration)
    opening = text.index("{", start)
    depth = 0
    for index in range(opening, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1:index]
    raise ValueError(f"unterminated initializer: {declaration}")


def parse_simple_enum(text: str, declaration: str, prefix: str) -> dict[str, int]:
    body = initializer(text, declaration)
    values: dict[str, int] = {}
    current = -1
    for raw in body.split(","):
        entry = re.sub(r"//.*", "", raw).strip()
        if not entry or not entry.startswith(prefix):
            continue
        if "=" in entry:
            name, expression = (part.strip() for part in entry.split("=", 1))
            if not re.fullmatch(r"-?(?:0x[0-9a-fA-F]+|\d+)", expression):
                # Multiplayer LEVELID aliases follow the table used here.
                continue
            current = int(expression, 0)
        else:
            name = entry
            current += 1
        values[name] = current
    return values


def generate(root: Path) -> str:
    constants_path = root / "src/bondconstants.h"
    setup_path = root / "src/game/music_0D2720.c"
    table_path = root / "assets/music/music.s"
    constants = constants_path.read_text()
    setup = setup_path.read_text()
    table = table_path.read_text()

    level_ids = parse_simple_enum(constants, "typedef enum LEVELID", "LEVELID_")
    tracks = parse_simple_enum(constants, "typedef enum MUSIC_TRACKS", "M_")
    ordered_tracks = sorted(tracks, key=tracks.get)
    if [tracks[name] for name in ordered_tracks] != list(range(63)):
        raise ValueError("MUSIC_TRACKS is no longer a contiguous 63-entry table")

    table_body = table[
        table.index("table_music_data:") + len("table_music_data:"):
        table.index("table_music_data_end:")
    ]
    asset_stems = re.findall(r"\bmusic_table_entry\s+(M[A-Za-z0-9_]+)", table_body)
    if len(asset_stems) != len(ordered_tracks):
        raise ValueError(
            f"music table has {len(asset_stems)} assets for {len(ordered_tracks)} tracks"
        )

    setup_body = initializer(setup, "struct music_setup music_setup_entries[]")
    rows = re.findall(
        r"\{\s*(LEVELID_[A-Z0-9_]+)\s*,\s*(M_[A-Z0-9_]+|-?\d+|0x[0-9A-Fa-f]+)\s*,"
        r"\s*(M_[A-Z0-9_]+|-?\d+|0x[0-9A-Fa-f]+)\s*,"
        r"\s*(M_[A-Z0-9_]+|-?\d+|0x[0-9A-Fa-f]+)\s*\}",
        setup_body,
    )
    if len(rows) != 23:
        raise ValueError(f"expected 23 canonical stage music rows, found {len(rows)}")

    def value(token: str, values: dict[str, int]) -> int:
        if token in values:
            return values[token]
        parsed = int(token, 0)
        return -1 if parsed == 0xFFFF else parsed

    evidence = [constants_path, setup_path, table_path]
    output = [
        "/* Generated by scripts/generate_original_stage_music.py; do not edit. */",
        "/* Canonical evidence SHA-256:",
    ]
    for path in evidence:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        output.append(f" * {path.relative_to(root).as_posix()} {digest}")
    output.extend([" */", ""])
    for index, (track_symbol, asset_stem) in enumerate(zip(ordered_tracks, asset_stems)):
        output.append(
            f'GE_ORIGINAL_MUSIC_TRACK({index}, "{track_symbol}", '
            f'"music/{asset_stem}.bin")'
        )
    output.append("")
    for level_symbol, main, background, xtrack in rows:
        output.append(
            f'GE_ORIGINAL_STAGE_MUSIC({level_ids[level_symbol]}, "{level_symbol}", '
            f'{value(main, tracks)}, {value(background, tracks)}, '
            f'{value(xtrack, tracks)})'
        )
    output.append("")
    return "\n".join(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.root.resolve()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
